routes/web.php
<?php

//SUPER ADMIN
use App\Http\Controllers\SuperAdminController;


use App\Http\Controllers\BarangController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DetailPembelianController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\KeuntunganController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\MerekController;
use App\Http\Controllers\PelangganController;
use App\Http\Controllers\PerusahaanController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SatuanController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\UsersController;

// Informasi Kas
use App\Http\Controllers\KasMasukController;
use App\Http\Controllers\KasKeluarController;

// Transaksi
use App\Http\Controllers\TransaksiPenjualanController;
use App\Http\Controllers\ListTransaksiPenjualanController;
use App\Http\Controllers\DetailPenjualanController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\PDFController;
use App\Http\Controllers\PembelianController;
use App\Http\Controllers\ListTransaksiPembelianController;

use App\Http\Controllers\HutangController;
use App\Http\Controllers\ListReturPembelianController;
use App\Http\Controllers\PiutangController;
use App\Http\Controllers\ReturPenjualanController;
use App\Http\Controllers\ListReturPenjualanController;
use App\Http\Controllers\ReturPembelianController;
use App\Http\Controllers\StokOpnameController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth'])->group(function () {
        Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
        // Route::patch('/manage-perusahaan/perbarui/{id}', [SuperAdminController::class, 'perbarui'])->name('manage.perbarui');

        Route::group(['prefix' => 'super_admin', 'middleware' => 'cek-hak-akses:super_admin', 'as' => 'super_admin.'], function () {
                Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

                Route::resource('/users', UsersController::class);
                Route::get('/users-tambah', [UsersController::class, 'index2'])->name('pegawai2');
                Route::post('/users-tambah', [UsersController::class, 'store']);
                Route::get('/profile', [UsersController::class, 'profile'])->name('profile');
                Route::post('/profile', [UsersController::class, 'profileUpdate']);
                Route::get('/profile/cards', [UsersController::class, 'card'])->name('profile.cards');

                Route::get('/changePW', [UsersController::class, 'changePW'])->name('changePW');
                Route::post('/changePW', [UsersController::class, 'changePWUpdate']);

                Route::resource('/manage-perusahaan', SuperAdminController::class);
                Route::post('/manage-perusahaan/data', [SuperAdminController::class, 'table'])->name('manage.data');
                Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
        });

        Route::group(['prefix' => 'owner', 'middleware' => 'cek-hak-akses:owner', 'as' => 'owner.'], function () {
                Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
                Route::resource('/kategori', KategoriController::class);
                Route::resource('/merek', MerekController::class);
                Route::resource('/satuan', SatuanController::class);
                Route::resource('/perusahaan', PerusahaanController::class);    

                Route::resource('/users', UsersController::class);
                Route::get('/users-tambah', [UsersController::class, 'index2'])->name('pegawai2');
                Route::post('/users-tambah', [UsersController::class, 'store']);
                Route::get('/profile', [UsersController::class, 'profile'])->name('profile');
                Route::post('/profile', [UsersController::class, 'profileUpdate']);
                Route::get('/profile/cards', [UsersController::class, 'card'])->name('profile.cards');

                Route::get('/changePW', [UsersController::class, 'changePW'])->name('changePW');
                Route::post('/changePW', [UsersController::class, 'changePWUpdate']);

                Route::get('/keuntungan', [KeuntunganController::class, 'index'])->name('keuntungan');
                Route::post('/keuntungan', [KeuntunganController::class, 'store'])->name('keuntungan.store');
                
                // Stok opname
                Route::get('/stock-opname', [StokOpnameController::class, 'index'])->name('stockOpname');
                Route::post('/stock-opname', [StokOpnameController::class, 'updateStock']);      
                
                // Laporan
                Route::get('/list-pelanggan-terbaik', [LaporanController::class, 'indexBestPelanggan'])->name('list-b-pelanggan.index');
                Route::post('/list-pelanggan-terbaik/data/{awal}/{akhir}', [LaporanController::class, 'getDataBestPelanggan'])->name('list-b-pelanggan.data');
                Route::get('/list-pelanggan-terbaik/download/{awal}/{akhir}', [LaporanController::class, 'DownloadBestPelanggan'])->name('list-b-pelanggan.download');
                Route::get('/list-pelanggan-terbaik/pdf/{awal}/{akhir}', [LaporanController::class, 'PrintPDFBestPelanggan'])->name('list-b-pelanggan.print');

                Route::get('/laporan-kas', [LaporanController::class, 'indexLaporanKas'])->name('laporan-kas.index');
                Route::post('/laporan-kas-masuk/data/{awal}/{akhir}', [LaporanController::class, 'dataLaporanKasMasuk'])->name('laporan-kas-masuk.data');
                Route::post('/laporan-kas-keluar/data/{awal}/{akhir}', [LaporanController::class, 'dataLaporanKasKeluar'])->name('laporan-kas-keluar.data');
                Route::get('/laporan-kas/download/{awal}/{akhir}', [LaporanController::class, 'DownloadKas'])->name('laporan-kas.download');
                Route::get('/laporan-kas/pdf/{awal}/{akhir}', [LaporanController::class, 'PrintPDFKas'])->name('laporan-kas.print');
                
                Route::get('/laporan-penjualan', [LaporanController::class, 'indexLaporanPenjualan'])->name('laporan-penjualan.index');
                Route::post('/laporan-penjualan/data/{awal}/{akhir}', [LaporanController::class, 'dataLaporanPenjualan'])->name('laporan-penjualan.data');
                Route::get('/laporan-penjualan/download/{awal}/{akhir}', [LaporanController::class, 'DownloadPenjualan'])->name('laporan-penjualan.download');
                Route::get('/laporan-penjualan/pdf/{awal}/{akhir}', [LaporanController::class, 'PrintPDFPenjualan'])->name('laporan-penjualan.print');

                Route::get('/laporan-pembelian', [LaporanController::class, 'indexLaporanPembelian'])->name('laporan-pembelian.index');
                Route::post('/laporan-pembelian/data/{awal}/{akhir}', [LaporanController::class, 'dataLaporanPembelian'])->name('laporan-pembelian.data');
                Route::get('/laporan-pembelian/download/{awal}/{akhir}', [LaporanController::class, 'DownloadPembelian'])->name('laporan-pembelian.download');
                Route::get('/laporan-pembelian/pdf/{awal}/{akhir}', [LaporanController::class, 'PrintPDFPembelian'])->name('laporan-pembelian.print');

                Route::get('/laporan-stok', [LaporanController::class, 'indexLaporanStok'])->name('laporan-stok.index');
                Route::post('/laporan-stok/data/{merek}/{kategori}', [LaporanController::class, 'dataLaporanStok'])->name('laporan-stok.data');
                Route::get('/laporan-stok/download/{merek}/{kategori}', [LaporanController::class, 'DownloadStok'])->name('laporan-stok.download');
                Route::get('/laporan-stok/pdf/{merek}/{kategori}', [LaporanController::class, 'PrintPDFStok'])->name('laporan-stok.print');

                Route::get('/laporan-kesesuaian-stok', [LaporanController::class, 'indexLaporanKesesuaianStok'])->name('laporan-kesesuaian-stok.index');
                Route::post('/laporan-kesesuaian-stok/data/{awal}/{akhir}/{merek}/{kategori}', [LaporanController::class, 'dataLaporanKesesuaianStok'])->name('laporan-kesesuaian-stok.data');
                Route::get('/laporan-kesesuaian-stok/download/{awal}/{akhir}/{merek}/{kategori}', [LaporanController::class, 'DownloadKesesuaianStok'])->name('laporan-kesesuaian-stok.download');
                Route::get('/laporan-kesesuaian-stok/pdf/{awal}/{akhir}/{merek}/{kategori}', [LaporanController::class, 'PrintPDFKesesuaianStok'])->name('laporan-kesesuaian-stok.print');
        
                Route::get('/laporan-hutang', [LaporanController::class, 'indexLaporanHutang'])->name('laporan-hutang.index');
                Route::post('/laporan-hutang/data/{awal}/{akhir}', [LaporanController::class, 'dataLaporanHutang'])->name('laporan-hutang.data');
                Route::get('/laporan-hutang/download/{awal}/{akhir}', [LaporanController::class, 'DownloadHutang'])->name('laporan-hutang.download');
                Route::get('/laporan-hutang/pdf/{awal}/{akhir}', [LaporanController::class, 'PrintPDFHutang'])->name('laporan-hutang.print');
                
                Route::get('/laporan-piutang', [LaporanController::class, 'indexLaporanPiutang'])->name('laporan-piutang.index');
                Route::post('/laporan-piutang/data/{awal}/{akhir}', [LaporanController::class, 'dataLaporanPiutang'])->name('laporan-piutang.data');
                Route::get('/laporan-piutang/download/{awal}/{akhir}', [LaporanController::class, 'DownloadPiutang'])->name('laporan-piutang.download');
                Route::get('/laporan-piutang/pdf/{awal}/{akhir}', [LaporanController::class, 'PrintPDFPiutang'])->name('laporan-piutang.print');


                Route::get('/laporan-harian', [LaporanController::class, 'indexLaporanHarian'])->name('laporan-harian.index');

resources/views/laporan/laporan-pembelian/index.blade.php
@extends('templates.layout')

@section('title')
<title>Laporan Pembelian | {{ $cPerusahaan->nama }}</title>
@endsection

@section('page')
Laporan Pembelian
@endsection

@section('breadcrumb')
@parent
Laporan Pembelian
@endsection

@push('styles')
@endpush

@section('contents')

<!-- Main content -->
<section class="content">
    <div class="row mx-3">
        <div class="col-md-12 p-2 mb-3" style="background-color: white">
            <div class="box mb-4">
                <div class="box-body table-responsive ">
                    @if (auth()->user()->hak_akses == 'admin')
                        <form action="{{ route('admin.laporan-pembelian.index') }}" method="get">
                    @elseif(auth()->user()->hak_akses == 'owner')             
                        <form action="{{ route('owner.laporan-pembelian.index') }}" method="get">
                    @endif    
                        <div class="form-group row mt-4 ml-3 ">
                            <label for="tanggal_awal" class="col-lg-1 control-label mr-3">Tanggal Awal</label>
                            <div class="col-md-3 mr-5 mt-3">
                                <input type="date" name="tanggal_awal" id="tanggal_awal" class="flatpickr form-control" required autofocus readonly value="{{ request('tanggal_awal') }}" style="border-radius: 0 !important;">
                                <span class="help-block with-errors"></span>
                            </div>
                            
                            <h5 class="mr-5 mx-3 my-2 mt-3" for="" class="col-md-2"><small><b>s/d</b></small></h5>

                            <label for="tanggal_akhir" class="col-lg-1 mr-2 control-label">Tanggal Akhir</label>
                            <div class="col-md-3 mr-5 mt-3">
                                <input type="date" name="tanggal_akhir" id="tanggal_akhir" class="flatpickr form-control" required readonly value="{{ request('tanggal_akhir') }}" style="border-radius: 0 !important;">
                                <span class="help-block with-errors"></span>
                            </div>

                            <div class="form-group row ml-3 mb-3 mt-3">
                                <button type="" class="btn btn-xs btn-primary"><i class="fa fa-search"></i> Cari</button>
                            </div>
                        </div>
                    </form>

                    <div class="print text-center p-2 mb-1 d-flex justify-content-start" style=" border-bottom: 1px solid grey;">
                        <small style="color:gray;" class="">Print Section</small>
                        {{-- <hr style="height:2px"> --}}
                    </div>
                    
                    <div class="button-group mb-2">  
                        @if (auth()->user()->hak_akses == 'admin')
                            <a href="{{ route('admin.laporan-pembelian.print', [$tanggalAwal, $tanggalAkhir]) }}" class="ml-2 mb-3 mt-3 btn btn-sm btn-danger text-end"><i class="fa fa-file-pdf"></i> Print PDF</a>
                            <a href="{{ route('admin.laporan-pembelian.download', [$tanggalAwal, $tanggalAkhir] ) }}" class="mb-3 ml-2 mt-3 btn btn-sm btn-success text-end"><i class="fa fa-download"></i> Download PDF</a>          
                        @elseif(auth()->user()->hak_akses == 'owner') 
                            <a href="{{ route('owner.laporan-pembelian.print', [$tanggalAwal, $tanggalAkhir]) }}" class="ml-2 mb-3 mt-3 btn btn-sm btn-danger text-end"><i class="fa fa-file-pdf"></i> Print PDF</a>
                            <a href="{{ route('owner.laporan-pembelian.download', [$tanggalAwal, $tanggalAkhir] ) }}" class="mb-3 ml-2 mt-3 btn btn-sm btn-success text-end"><i class="fa fa-download"></i> Download PDF</a>               
                        @endif               
                                 
                    </div>
                {{-- <a href="{{ route('admin.list-transaksi.export_pdf', [$tanggalAwal, $tanggalAkhir] ) }}" target="_blank" class="btn btn-danger btn-sm btn-flat" ><i class="bi bi-filetype-pdf"></i> Export PDF</a> --}}
                    <br>
                    <h3 class="text-center">{{ $cPerusahaan->nama }}</h3>
                    <h5 style="text-align:center;">Laporan Pembelian {{ tanggal_indonesia($tanggalAwal) }}</h5>
                    <h5 style="text-align:center;" >s/d {{ tanggal_indonesia($tanggalAkhir) }}</h5>
                    <br>

                    <!-- DataTable with Hover -->
                    <div class="col-lg-12">
                        <div class="table-responsive p-3">
                            <h5 class="mb-3">Pembelian</h5>
                            <table style="border-left: 0.02px solid lightgrey" class="table align-items-center mb-5 table-bordered table-striped table-flush table-hover text-center table-responsive dt-responsive table-pembelian" id="dataTableHover">
                                <thead class="table-dark">
                                    <tr>
                                        <th width="11%" class="text-center">Tanggal</th>
                                        <th width="8%" class="text-center">Kode</th>
                                        <th width="16%" class="text-center">Nama Barang</th>
                                        <th width="8%" class="text-center">QTY</th>
                                        <th width="17%" class="text-center">Total Pembelian</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if ($detPembelian != NULL)
                                        @foreach ($detPembelian as $dp)
                                            <tr>
                                                <td class="text-center">{{ tanggal_indonesia($dp->tgl, false) }}</td>
                                                <td class="text-center"><span class="badge" style="background-color:#2f3d57; color:white;">{{ $dp->kode }}</span></td>
                                                <td class="text-center">{{ $dp->nama_barang }}</td>
                                                <td class="text-center">{{ $dp->qty }}</td>
                                                @if ($dp->diskon == 0)
                                                    <td class="text-center" id="">{{ 'Rp.' . format_uang($dp->qty * $dp->harga_beli) }}</td>
                                                @else
                                                    <td class="text-center" id="">{{ 'Rp.' . format_uang($dp->qty * $dp->harga_beli - (($dp->qty * $dp->harga_beli) * $dp->diskon/100)) }}</td>
                                                @endif
                                            </tr>
                                        @endforeach
                                        <tr class="table-info">
                                            <td class="text-center" colspan="4">Total</td>
                                            <td class="text-center total-omset">{{ 'Rp. '. format_uang($totalBeli) }}</td>
                                        </tr>
                                    @else
                                        <tr>
                                            <td colspan="5" class="text-center" style="color:grey; font-size:17px;">Tidak ada data</td>    
                                        </tr>  
                                    @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
@endsection

@push('scripts')
<script>
    $(".flatpickr").flatpickr({
        enableTime: false,
        dateFormat: "d-m-Y",
        autoclose: true,
    });

    $('.table-pembelian').DataTable({
        searching: false,
        info: false,
        paging:false,
        processing:false,
        language: {
            emptyTable: "Tidak Ada Data"
        }
    });

    // @if(auth()->user()->hak_akses == 'owner') 
    //     var pembelian = "{{ route('owner.laporan-pembelian.data', [$tanggalAwal, $tanggalAkhir]) }}";
    // @elseif(auth()->user()->hak_akses == 'admin') 
    //     var pembelian = "{{ route('admin.laporan-pembelian.data', [$tanggalAwal, $tanggalAkhir]) }}";
    // @endif
    // let table_pembelian;
        // $('.table-pembelian').DataTable({
                // searching: false,
                // info: false,
                // paging:false,
                // bFilter:false,
        // });
    //     ajax: {
    //         url: pembelian,
    //         type: "POST",
    //         data: {  
    //             _token: '{{ csrf_token() }}'
    //         }
    //     },
    //     columns: [
    //         // {data:'DT_RowIndex', searchable: false, sortable: false},
    //         {data:'tgl'},
    //         {data:'kode'},
    //         {data:'nama_barang'},
    //         {data:'qty'},
    //         {data:'total_pembelian'},
    //     ]
    // });

</script>
@endpush

resources/views/laporan/laporan-pembelian/pdf.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Laporan Pembelian</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <style>
       table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        tr {
            border-top: 1.325px solid black;
            border-bottom: 1.325px solid black;
        }

        td, th {
            border: 1.325px solid black;
            border-bottom: 1.325px solid black;
            text-align: left;
            padding: 8px;
        }
    </style>
  </head>
  <body>
    <small class="convert-tgl" style="visibility: hidden;">
        {{ $no = 1 }}
    </small>
    <h2 class="text-center">{{ $cPerusahaan->nama }}</h2>
    <h3 class="text-center">Laporan Pembelian</h3>
    <h5 class="text-center mb-4">
        Tanggal {{ tanggal_indonesia($tglAwal, false) }}
        s/d
        Tanggal {{ tanggal_indonesia($akhir, false) }}
    </h5>

    <div class="col-md-12">
        <div class="table-responsive p-2">
            <table class="table align-items-center mb-5 table-bordered table-striped table-flush table-hover text-center table-Pembelian" id="dataTableHover">
                {{-- <thead class="table-primary">
                    <tr>
                        <th width="4%" class="text-center">No</th>
                        <th width="9%" class="text-center">Tanggal</th>
                        <th width="8%" class="text-center">Kode</th>
                        <th width="16%" class="text-center">Nama Barang</th>
                        <th width="8%" class="text-center">QTY</th>
                        <th width="17%" class="text-center">Total Pembelian</th>
                    </tr>
                </thead> --}}
                <tbody>
                    <th width="4%" class="text-center">No</th>
                    <th width="9%" class="text-center">Tanggal</th>
                    <th width="8%" class="text-center">Kode</th>
                    <th width="16%" class="text-center">Nama Barang</th>
                    <th width="8%" class="text-center">QTY</th>
                    <th width="17%" class="text-center">Total Pembelian</th>
                    @if ($detPembelian != NULL)
                        @foreach ($detPembelian as $dp)
                            <tr>
                                <td class="text-center">{{ $no++ }}</td>
                                <td class="text-center">{{ tanggal_indonesia($dp->tgl,false) }}</td>
                                <td class="text-center">{{ $dp->kode }}</td>
                                <td class="text-center">{{ $dp->nama_barang }}</td>
                                <td class="text-center">{{ $dp->qty }}</td>
                                {{-- <td class="text-center" id="omset">{{ 'Rp.' . format_uang($dp->qty * $dp->harga_beli) }}</td> --}}
                                @if ($dp->diskon == 0)
                                    <td class="text-center ">{{ 'Rp. ' . format_uang(($dp->harga_beli) * $dp->qty) }}</td>
                                @else 
                                    <td class="text-center" >{{ 'Rp. ' . format_uang((($dp->harga_beli) * $dp->qty) - ( ($dp->harga_beli) * $dp->qty) * $dp->diskon/100) }}</td>
                                @endif
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="7" class="text-center" style="color:grey; font-size:17px;">Tidak ada data</td>    
                        </tr>  
                    @endif
                    <tr>
                        <td class="text-center" colspan="5"><b>Total</b></td>
                        <td id="totalU" class="text-center">{{ 'Rp. '. format_uang($totalBeli) }}</td>
                    </tr>
                </tbody>
                {{-- <tfoot>
                    <tr>
                        <td class="text-center" colspan="5"><b>Total</b></td>
                        <td id="totalU" class="text-center">{{ 'Rp. '. format_uang($totalBeli) }}</td>
                    </tr>
                </tfoot> --}}
            </table>
            
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/laporan/laporan-pembelian/print.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Laporan Pembelian</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        tr {
            border-top: 1.325px solid black;
            border-bottom: 1.325px solid black;
        }

        td, th {
            border: 1.325px solid black;
            border-bottom: 1.325px solid black;
            text-align: left;
            padding: 8px;
        }

        .button {
            /* text-align-last: right; */
            /* align-content: flex-end; */
            /* align-items: flex-end; */
            margin-left: 20px;
        }
        @page {
            size: A4;
            margin: 0;
            }
        @media print {
            html, body {
                width: 210mm;
                padding-right:9.5mm;
                padding-left:6.5mm;
                padding-top:5.7mm;
                padding-bottom:5.7mm;
                height: 297mm;
            }
            /* ... the rest of the rules ... */
        }
    </style>

<?php
    $style = '
    <style>
        * {
            font-family: "Gill Sans MT", cursive;
        }
        p {
            display: block;
            margin: 4px;
            font-size: 10pt;
        }
        .text-center {
            text-align: center;
        }
        .text-right {
            text-align: right;
        }

    ';
?>
<?php 
    $style .= 
        ! empty($_COOKIE['innerHeight'])
            ? $_COOKIE['innerHeight'] .'mm; }'
            : '}';
    ?>
    <?php
    $style .= '
            .btn-print {
                display: none;
            }
        }
    </style>
    ';
?>

{!! $style !!}
</head>
  <body onload="window.print()">
    <div class="button ml-4 align-items-end">
        @if (auth()->user()->hak_akses == 'admin')
            <a href="{{ route('admin.laporan-pembelian.index') }}" class="mb-3 mt-3 btn btn-sm btn-secondary ml-4 d-print-none"><i class="fas fa-arrow-rotate-left"></i> Back</a>
        @elseif (auth()->user()->hak_akses == 'owner')
            <a href="{{ route('owner.laporan-pembelian.index') }}" class="mb-3 mt-3 btn btn-sm btn-secondary ml-4 d-print-none"><i class="fas fa-arrow-rotate-left"></i> Back</a>
        @endif
        <button onclick="window.print()" class="mb-3 mt-3 btn btn-sm btn-danger ml-4 d-print-none"><i class="fa-solid fa-print"></i> Print PDF</button>
    </div>

    <small class="convert-tgl" style="visibility: hidden">
        {{ $no = 1 }}
    </small>
    <h2 class="text-center">{{ $cPerusahaan->nama }}</h2>
    <h3 class="text-center">Laporan Penjualan</h3>
    <h5 class="text-center mb-4">
        Tanggal {{ tanggal_indonesia($tglAwal, false) }}
        s/d
        Tanggal {{ tanggal_indonesia($akhir, false) }}
    </h5>

    <div class="col-md-12 mt-3">
        <div class="table-responsive p-2">
            <table border="1" class="table mb-5 table-bordered table-striped table-penjualan" id="dataTableHover">
                {{-- <thead class="table-secondary">
                    <tr>
                        <th width="4%" class="text-center">No</th>
                        <th width="9%" class="text-center">Tanggal</th>
                        <th width="8%" class="text-center">Kode</th>
                        <th width="16%" class="text-center">Nama Barang</th>
                        <th width="8%" class="text-center">QTY</th>
                        <th width="17%" class="text-center">Total Pembelian</th>
                    </tr>
                </thead> --}}
                <tbody>
                    <th width="4%" class="text-center">No</th>
                    <th width="9%" class="text-center">Tanggal</th>
                    <th width="8%" class="text-center">Kode</th>
                    <th width="16%" class="text-center">Nama Barang</th>
                    <th width="8%" class="text-center">QTY</th>
                    <th width="17%" class="text-center">Total Pembelian</th>
                    @if ($detPembelian != NULL)
                        @foreach ($detPembelian as $dp)
                            <tr>
                                <td class="text-center">{{ $no++ }}</td>
                                <td class="text-center">{{ tanggal_indonesia($dp->tgl,false) }}</td>
                                <td class="text-center">{{ $dp->kode }}</td>
                                <td class="text-center">{{ $dp->nama_barang }}</td>
                                <td class="text-center">{{ $dp->qty }}</td>
                                {{-- <td class="text-center" id="omset">{{ 'Rp.' . format_uang($dp->qty * $dp->harga_beli) }}</td> --}}
                                @if ($dp->diskon == 0)
                                    <td class="text-center ">{{ 'Rp. ' . format_uang(($dp->harga_beli) * $dp->qty) }}</td>
                                @else 
                                    <td class="text-center" >{{ 'Rp. ' . format_uang((($dp->harga_beli) * $dp->qty) - ( ($dp->harga_beli) * $dp->qty) * $dp->diskon/100) }}</td>
                                @endif
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="7" class="text-center" style="color:grey; font-size:17px;">Tidak ada data</td>    
                        </tr>  
                    @endif
                    <tr>
                        <td class="text-center" colspan="5"><b>Total</b></td>
                        <td id="totalO" class="text-center">{{ 'Rp. '. format_uang($totalBeli) }}</td>
                    </tr>
                </tbody>
                {{-- <tfoot>
                    <tr>
                        <td class="text-center" colspan="5"><b>Total</b></td>
                        <td id="totalO" class="text-center">{{ 'Rp. '. format_uang($totalBeli) }}</td>
                    </tr>
                </tfoot> --}}
            </table>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script>
        function remove() {
            var btn =$('.button').html();
            btn.remove();
        }

        $('div.button-print').hide();
    </script>

    </body>
</html>