routes/web.php
<?php

//SUPER ADMIN
use App\Http\Controllers\SuperAdminController;


use App\Http\Controllers\BarangController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DetailPembelianController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\KeuntunganController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\MerekController;
use App\Http\Controllers\PelangganController;
use App\Http\Controllers\PerusahaanController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SatuanController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\UsersController;

// Informasi Kas
use App\Http\Controllers\KasMasukController;
use App\Http\Controllers\KasKeluarController;

// Transaksi
use App\Http\Controllers\TransaksiPenjualanController;
use App\Http\Controllers\ListTransaksiPenjualanController;
use App\Http\Controllers\DetailPenjualanController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\PDFController;
use App\Http\Controllers\PembelianController;
use App\Http\Controllers\ListTransaksiPembelianController;

use App\Http\Controllers\HutangController;
use App\Http\Controllers\ListReturPembelianController;
use App\Http\Controllers\PiutangController;
use App\Http\Controllers\ReturPenjualanController;
use App\Http\Controllers\ListReturPenjualanController;
use App\Http\Controllers\ReturPembelianController;
use App\Http\Controllers\StokOpnameController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth'])->group(function () {
        Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
        // Route::patch('/manage-perusahaan/perbarui/{id}', [SuperAdminController::class, 'perbarui'])->name('manage.perbarui');

        Route::group(['prefix' => 'super_admin', 'middleware' => 'cek-hak-akses:super_admin', 'as' => 'super_admin.'], function () {
                Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

                Route::resource('/users', UsersController::class);
                Route::get('/users-tambah', [UsersController::class, 'index2'])->name('pegawai2');
                Route::post('/users-tambah', [UsersController::class, 'store']);
                Route::get('/profile', [UsersController::class, 'profile'])->name('profile');
                Route::post('/profile', [UsersController::class, 'profileUpdate']);
                Route::get('/profile/cards', [UsersController::class, 'card'])->name('profile.cards');

                Route::get('/changePW', [UsersController::class, 'changePW'])->name('changePW');
                Route::post('/changePW', [UsersController::class, 'changePWUpdate']);

                Route::resource('/manage-perusahaan', SuperAdminController::class);
                Route::post('/manage-perusahaan/data', [SuperAdminController::class, 'table'])->name('manage.data');
                Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
        });

        Route::group(['prefix' => 'owner', 'middleware' => 'cek-hak-akses:owner', 'as' => 'owner.'], function () {
                Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
                Route::resource('/kategori', KategoriController::class);
                Route::resource('/merek', MerekController::class);
                Route::resource('/satuan', SatuanController::class);
                Route::resource('/perusahaan', PerusahaanController::class);    

                Route::resource('/users', UsersController::class);
                Route::get('/users-tambah', [UsersController::class, 'index2'])->name('pegawai2');
                Route::post('/users-tambah', [UsersController::class, 'store']);
                Route::get('/profile', [UsersController::class, 'profile'])->name('profile');
                Route::post('/profile', [UsersController::class, 'profileUpdate']);
                Route::get('/profile/cards', [UsersController::class, 'card'])->name('profile.cards');

                Route::get('/changePW', [UsersController::class, 'changePW'])->name('changePW');
                Route::post('/changePW', [UsersController::class, 'changePWUpdate']);

                Route::get('/keuntungan', [KeuntunganController::class, 'index'])->name('keuntungan');
                Route::post('/keuntungan', [KeuntunganController::class, 'store'])->name('keuntungan.store');
                
                // Stok opname
                Route::get('/stock-opname', [StokOpnameController::class, 'index'])->name('stockOpname');
                Route::post('/stock-opname', [StokOpnameController::class, 'updateStock']);      
                
                // Laporan
                Route::get('/list-pelanggan-terbaik', [LaporanController::class, 'indexBestPelanggan'])->name('list-b-pelanggan.index');
                Route::post('/list-pelanggan-terbaik/data/{awal}/{akhir}', [LaporanController::class, 'getDataBestPelanggan'])->name('list-b-pelanggan.data');
                Route::get('/list-pelanggan-terbaik/download/{awal}/{akhir}', [LaporanController::class, 'DownloadBestPelanggan'])->name('list-b-pelanggan.download');
                Route::get('/list-pelanggan-terbaik/pdf/{awal}/{akhir}', [LaporanController::class, 'PrintPDFBestPelanggan'])->name('list-b-pelanggan.print');

                Route::get('/laporan-kas', [LaporanController::class, 'indexLaporanKas'])->name('laporan-kas.index');
                Route::post('/laporan-kas-masuk/data/{awal}/{akhir}', [LaporanController::class, 'dataLaporanKasMasuk'])->name('laporan-kas-masuk.data');
                Route::post('/laporan-kas-keluar/data/{awal}/{akhir}', [LaporanController::class, 'dataLaporanKasKeluar'])->name('laporan-kas-keluar.data');
                Route::get('/laporan-kas/download/{awal}/{akhir}', [LaporanController::class, 'DownloadKas'])->name('laporan-kas.download');
                Route::get('/laporan-kas/pdf/{awal}/{akhir}', [LaporanController::class, 'PrintPDFKas'])->name('laporan-kas.print');
                
                Route::get('/laporan-penjualan', [LaporanController::class, 'indexLaporanPenjualan'])->name('laporan-penjualan.index');
                Route::post('/laporan-penjualan/data/{awal}/{akhir}', [LaporanController::class, 'dataLaporanPenjualan'])->name('laporan-penjualan.data');
                Route::get('/laporan-penjualan/download/{awal}/{akhir}', [LaporanController::class, 'DownloadPenjualan'])->name('laporan-penjualan.download');
                Route::get('/laporan-penjualan/pdf/{awal}/{akhir}', [LaporanController::class, 'PrintPDFPenjualan'])->name('laporan-penjualan.print');

                Route::get('/laporan-pembelian', [LaporanController::class, 'indexLaporanPembelian'])->name('laporan-pembelian.index');
                Route::post('/laporan-pembelian/data/{awal}/{akhir}', [LaporanController::class, 'dataLaporanPembelian'])->name('laporan-pembelian.data');
                Route::get('/laporan-pembelian/download/{awal}/{akhir}', [LaporanController::class, 'DownloadPembelian'])->name('laporan-pembelian.download');
                Route::get('/laporan-pembelian/pdf/{awal}/{akhir}', [LaporanController::class, 'PrintPDFPembelian'])->name('laporan-pembelian.print');

                Route::get('/laporan-stok', [LaporanController::class, 'indexLaporanStok'])->name('laporan-stok.index');
                Route::post('/laporan-stok/data/{merek}/{kategori}', [LaporanController::class, 'dataLaporanStok'])->name('laporan-stok.data');
                Route::get('/laporan-stok/download/{merek}/{kategori}', [LaporanController::class, 'DownloadStok'])->name('laporan-stok.download');
                Route::get('/laporan-stok/pdf/{merek}/{kategori}', [LaporanController::class, 'PrintPDFStok'])->name('laporan-stok.print');

                Route::get('/laporan-kesesuaian-stok', [LaporanController::class, 'indexLaporanKesesuaianStok'])->name('laporan-kesesuaian-stok.index');
                Route::post('/laporan-kesesuaian-stok/data/{awal}/{akhir}/{merek}/{kategori}', [LaporanController::class, 'dataLaporanKesesuaianStok'])->name('laporan-kesesuaian-stok.data');
                Route::get('/laporan-kesesuaian-stok/download/{awal}/{akhir}/{merek}/{kategori}', [LaporanController::class, 'DownloadKesesuaianStok'])->name('laporan-kesesuaian-stok.download');
                Route::get('/laporan-kesesuaian-stok/pdf/{awal}/{akhir}/{merek}/{kategori}', [LaporanController::class, 'PrintPDFKesesuaianStok'])->name('laporan-kesesuaian-stok.print');
        
                Route::get('/laporan-hutang', [LaporanController::class, 'indexLaporanHutang'])->name('laporan-hutang.index');
                Route::post('/laporan-hutang/data/{awal}/{akhir}', [LaporanController::class, 'dataLaporanHutang'])->name('laporan-hutang.data');
                Route::get('/laporan-hutang/download/{awal}/{akhir}', [LaporanController::class, 'DownloadHutang'])->name('laporan-hutang.download');
                Route::get('/laporan-hutang/pdf/{awal}/{akhir}', [LaporanController::class, 'PrintPDFHutang'])->name('laporan-hutang.print');
                
                Route::get('/laporan-piutang', [LaporanController::class, 'indexLaporanPiutang'])->name('laporan-piutang.index');
                Route::post('/laporan-piutang/data/{awal}/{akhir}', [LaporanController::class, 'dataLaporanPiutang'])->name('laporan-piutang.data');
                Route::get('/laporan-piutang/download/{awal}/{akhir}', [LaporanController::class, 'DownloadPiutang'])->name('laporan-piutang.download');
                Route::get('/laporan-piutang/pdf/{awal}/{akhir}', [LaporanController::class, 'PrintPDFPiutang'])->name('laporan-piutang.print');


                Route::get('/laporan-harian', [LaporanController::class, 'indexLaporanHarian'])->name('laporan-harian.index');

resources/views/laporan/laporan-stok/index.blade.php
@extends('templates.layout')

@section('title')
<title>Laporan Stok | {{ $cPerusahaan->nama }}</title>
@endsection

@section('page')
Laporan Stok
@endsection

@section('breadcrumb')
@parent
Laporan Stok
@endsection

@push('styles')
@endpush

@section('contents')

<!-- Main content -->
<section class="content">
    <div class="row mx-3">
        <div class="col-md-12 p-2 mb-3" style="background-color: white">
            <div class="box mb-4">
                <div class="box-body table-responsive ">
                    @if (auth()->user()->hak_akses == 'admin')
                        <form action="{{ route('admin.laporan-stok.index') }}" method="get">
                    @elseif(auth()->user()->hak_akses == 'owner')             
                        <form action="{{ route('owner.laporan-stok.index') }}" method="get">
                    @endif  
                        <div class="form-group row mt-4 ml-3 ">
                            <label for="tanggal_awal" class="col-lg-1 control-label mr-3">Pilih Merek</label>
                            <div class="col-md-3 mr-5 mt-3">
                                <select name="merek" id="merek" class="form-control" required>
                                    <option value="">Pilih Merek</option>
                                    @foreach ($merek as $item )
                                        <option value="{{ $item->id }}">{{ $item->nama }}</option>   
                                    @endforeach
                                </select>
                                <span class="help-block with-errors"></span>

                            </div>
                            
                            <h5 class="mr-5 mx-3 my-2 mt-3" for="" class="col-md-2"><b></b></h5>

                            <label for="tanggal_akhir" class="col-lg-1 mr-2 control-label">Pilih Kategori</label>
                            <div class="col-md-3 mr-5 mt-3">
                                <select name="kategori" id="kategori" class="form-control" required>
                                    <option value="">Pilih Kategori</option>
                                    @foreach ($kategori as $item )
                                        <option value="{{ $item->id }}">{{ $item->nama }}</option>
                                    @endforeach
                                </select>
                                <span class="help-block with-errors"></span>
                            </div>

                            <div class="form-group row ml-3 mb-3 mt-3">
                                <button type="" class="btn btn-xs btn-primary"><i class="fa fa-search"></i> Cari</button>
                            </div>
                        </div>
                    </form>

                    <div class="print text-center p-2 mb-1 d-flex justify-content-start" style=" border-bottom: 1px solid grey;">
                        <small style="color:gray;" class="">Print Section</small>
                        {{-- <hr style="height:2px"> --}}
                    </div>
                    
                    <div class="button-group mb-2">   
                        @if (auth()->user()->hak_akses == 'admin')
                            <a href="{{ route('admin.laporan-stok.print', [$merk, $category]) }}" class="ml-2 mb-3 mt-3 btn btn-sm btn-danger text-end"><i class="fa fa-file-pdf"></i> Print PDF</a>
                            <a href="{{ route('admin.laporan-stok.download', [$merk, $category] ) }}" class="ml-2 mb-3 mt-3 btn btn-sm btn-success text-end"><i class="fa fa-download"></i> Download PDF</a>             
                        @elseif(auth()->user()->hak_akses == 'owner') 
                            <a href="{{ route('owner.laporan-stok.print', [$merk, $category]) }}" class="ml-2 mb-3 mt-3 btn btn-sm btn-danger text-end"><i class="fa fa-file-pdf"></i> Print PDF</a>
                            <a href="{{ route('owner.laporan-stok.download', [$merk, $category] ) }}" class="ml-2 mb-3 mt-3 btn btn-sm btn-success text-end"><i class="fa fa-download"></i> Download PDF</a>  
                        @endif             
                                 
                    </div>

                    <br>
                    <h3 class="text-center">{{ $cPerusahaan->nama }}</h3>
                    <h5 style="text-align:center;">Laporan Stok untuk Merek {{ $nameMerk }}</h5>
                    <h5 style="text-align:center;" >dan Kategori {{ $nameCategory }}</h5>
                    <br>
                {{-- <a href="{{ route('admin.list-transaksi.export_pdf', [$tanggalAwal, $tanggalAkhir] ) }}" target="_blank" class="btn btn-danger btn-sm btn-flat" ><i class="bi bi-filetype-pdf"></i> Export PDF</a> --}}

                    <!-- DataTable with Hover -->
                    <div class="col-lg-12">
                        <div class="table-responsive p-3">
                            <table class="table align-items-center mb-5 table-bordered table-striped table-flush table-hover text-center table-responsive dt-responsive  table-stok" id="dataTableHover">
                                <thead class="table-primary">
                                    <tr class="">
                                        <th width="7%" class="text-center" style="vertical-align:middle; margin:auto; text-align:center;">No</th>
                                        {{-- <th width="15%" class="text-center" style="vertical-align:middle; margin:auto; text-align:center;">No</th> --}}
                                        <th width="7%" class="text-center" style="vertical-align:middle; margin:auto; text-align:center;">Kode</th>
                                        <th width="16%" class="text-center" style="vertical-align:middle; margin:auto; text-align:center;">Nama Barang</th>
                                        <th width="10%" class="text-center" style="vertical-align:middle; margin:auto; text-align:center;">Merek</th>
                                        <th width="12%" class="text-center" style="vertical-align:middle; margin:auto; text-align:center;">Kategori</th>
                                        <th width="5%" class="text-center">Stock Minimal</th>
                                        <th width="5%" class="text-center">Stock Sekarang</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
@endsection

@push('scripts')
<script>
    $(".flatpickr").flatpickr({
        enableTime: false,
        dateFormat: "d-m-Y",
        autoclose: true,
    });

    @if(auth()->user()->hak_akses == 'owner') 
        var stok = "{{ route('owner.laporan-stok.data', [$merk, $category]) }}";
    @elseif(auth()->user()->hak_akses == 'admin') 
        var stok = "{{ route('admin.laporan-stok.data', [$merk, $category]) }}";
    @endif
   let table;
        table = $('.table-stok').DataTable({
        searching: false,
        info: false,
        // paging:false,
        bFilter:false,
        processing: false,
        responsive: true,
        autoWidth: false,
        serverSide: true,
        ajax: {
            url: stok,
            type: "POST",
            data: {  
                _token: '{{ csrf_token() }}'
            }
        },
        columns: [
            {data:'DT_RowIndex', searchable: false, sortable: false},
            // {data:'tgl'},
            {data:'kode'},
            {data:'nama_barang'},
            {data:'merek'},
            {data:'kategori'},
            {data:'stock_minimal'},
            {data:'stock_sekarang'},
        ]
    });

</script>
@endpush

resources/views/laporan/laporan-stok/pdf.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Laporan Stok</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <style>
       table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        tr {
            border-top: 1.325px solid black;
            border-bottom: 1.325px solid black;
        }

        td, th {
            border: 1.325px solid black;
            border-bottom: 1.325px solid black;
            text-align: left;
            padding: 8px;
        }
    </style>
  </head>
  <body>
    <small class="convert-tgl" style="visibility: hidden;">
        {{ $no = 1 }}
    </small>
    <h2 class="text-center">{{ $cPerusahaan->nama }}</h2>
    <h3 class="text-center">Laporan Stok</h3>
    <h5 class="text-center mb-4">
        Untuk merk {{ $merk->nama }}
        dan kategori {{ $category->nama }}
     </h5>

    {{-- <h4 class="mb-2 mt-5">Stok</h4> --}}
    <div class="col-md-12">
        <div class="table-responsive p-2">
            <table border="1" class="table mb-5 table-bordered table-striped table-stok" id="dataTableHover">
                <thead>
                    <tr class="">
                        <th width="4.2%" class="text-center" style="margin:auto; text-align:center;">No</th>
                        <th width="7.35%" class="text-center" style="margin:auto; text-align:center;">Kode</th>
                        <th width="15.4%" class="text-center" style="margin:auto; text-align:center;">Nama Barang</th>
                        <th width="8%" class="text-center" style="margin:auto; text-align:center;">Merek</th>
                        <th width="12%" class="text-center" style="margin:auto; text-align:center;">Kategori</th>
                        <th width="4.5%" class="text-center">Stock Minimal</th>
                        <th width="4.5%" class="text-center">Stock Sekarang</th>
                    </tr>
                </thead>
                <tbody>
                    @if ($stok != NULL)
                        @foreach ($stok as $s)
                            <tr>
                                <td class="text-center">{{ $no++ }}</td>
                                @foreach ($s as $item)
                                    <td class="text-center">{{ $item }}</td>
                                @endforeach
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="7" class="text-center" style="color:grey; font-size:17px;">Tidak ada data</td>    
                        </tr>  
                    @endif          
                </tbody>
            </table>          
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/laporan/laporan-stok/print.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Laporan Stok</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        tr {
            border-top: 1.325px solid black;
            border-bottom: 1.325px solid black;
        }

        td, th {
            border: 1.325px solid black;
            border-bottom: 1.325px solid black;
            text-align: left;
            padding: 8px;
        }

        .button {
            /* text-align-last: right; */
            /* align-content: flex-end; */
            /* align-items: flex-end; */
            margin-left: 20px;
        }
        @page {
            size: A4;
            margin: 0;
            }
        @media print {
            html, body {
                width: 210mm;
                padding-right:9.5mm;
                padding-left:6.5mm;
                padding-top:5.7mm;
                padding-bottom:5.7mm;
                height: 297mm;
            }
            /* ... the rest of the rules ... */
        }
    </style>

<?php
    $style = '
    <style>
        * {
            font-family: "Gill Sans MT", cursive;
        }
        p {
            display: block;
            margin: 4px;
            font-size: 10pt;
        }
        .text-center {
            text-align: center;
        }
        .text-right {
            text-align: right;
        }

    ';
?>
<?php 
    $style .= 
        ! empty($_COOKIE['innerHeight'])
            ? $_COOKIE['innerHeight'] .'mm; }'
            : '}';
    ?>
    <?php
    $style .= '
            .btn-print {
                display: none;
            }
        }
    </style>
    ';
?>

{!! $style !!}
</head>
  <body onload="window.print()">
    <div class="button ml-4 align-items-end">
        @if (auth()->user()->hak_akses == 'admin')
            <a href="{{ route('admin.laporan-stok.index') }}" class="mb-3 mt-3 btn btn-sm btn-secondary ml-4 d-print-none"><i class="fa-solid fa-arrow-rotate-left"></i> Back</a>
        @elseif (auth()->user()->hak_akses == 'owner')
            <a href="{{ route('owner.laporan-stok.index') }}" class="mb-3 mt-3 btn btn-sm btn-secondary ml-4 d-print-none"><i class="fa-solid fa-arrow-rotate-left"></i> Back</a>
        @endif
        <button onclick="window.print()" class="mb-3 mt-3 btn btn-sm btn-danger ml-4 d-print-none"><i class="fa-solid fa-print"></i> Print PDF</button>
    </div>

    <small class="convert-tgl" style="visibility: hidden">
        {{ $no = 1 }}
    </small>
    <h2 class="text-center">{{ $cPerusahaan->nama }}</h2>
    <h3 class="text-center">Laporan Stok</h3>
    <h5 class="text-center mb-4">
        Untuk merk {{ $merk->nama }}
        dan kategori {{ $category->nama }}
     </h5>

    <div class="col-md-12 mt-3">
        <div class="table-responsive p-2">
            <table border="1" class="table mb-5 table-bordered table-striped table-stok" id="dataTableHover">
                <thead class="table-secondary">
                    <tr>
                        <th width="4.2%" class="text-center" style="margin:auto; text-align:center;">No</th>
                        <th width="7.35%" class="text-center" style="margin:auto; text-align:center;">Kode</th>
                        <th width="15.4%" class="text-center" style="margin:auto; text-align:center;">Nama Barang</th>
                        <th width="8%" class="text-center" style="margin:auto; text-align:center;">Merek</th>
                        <th width="12%" class="text-center" style="margin:auto; text-align:center;">Kategori</th>
                        <th width="4.5%" class="text-center">Stock Minimal</th>
                        <th width="4.5%" class="text-center">Stock Sekarang</th>
                    </tr>
                </thead>
                <tbody>
                    @if ($stok != NULL)
                        @foreach ($stok as $s)
                            <tr>
                                <td class="text-center">{{ $no++ }}</td>
                                @foreach ($s as $item)
                                    <td class="text-center">{{ $item }}</td>
                                @endforeach
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="7" class="text-center" style="color:grey; font-size:17px;">Tidak ada data</td>    
                        </tr>  
                    @endif          
                </tbody>
            </table>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script>
        function remove() {
            var btn =$('.button').html();
            btn.remove();
        }

        $('div.button-print').hide();
    </script>

    </body>
</html>